/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.supermarket.view;

import edu.ijse.supermarket.connector.CustomerController;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import edu.ijse.supermarket.dto.CustomerDto;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class CustomerView extends javax.swing.JFrame {
    private static CustomerController custController = new CustomerController();
    /**
     * Creates new form CustomerView
     */
    public CustomerView() {
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLabel = new java.awt.Label();
        custIDLabel = new java.awt.Label();
        custIDTxt = new java.awt.TextField();
        custTitleLabel = new java.awt.Label();
        descriptionTxt = new java.awt.TextField();
        customerNameLabel = new java.awt.Label();
        custNameTxt = new java.awt.TextField();
        dobLabel = new java.awt.Label();
        salaryLabel = new java.awt.Label();
        qohTxt = new java.awt.TextField();
        unitPriceTxt = new java.awt.TextField();
        deleteCustBtn = new java.awt.Button();
        updateCustBtn = new java.awt.Button();
        saveCustBtn = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTbl = new javax.swing.JTable();
        custAddressLabel = new java.awt.Label();
        custAddressTxt = new java.awt.TextField();
        cityLabel = new java.awt.Label();
        cityTxt = new java.awt.TextField();
        provinceLabel = new java.awt.Label();
        provinceTxt = new java.awt.TextField();
        postalCodeTxt = new java.awt.TextField();
        postalCodeLabel = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerLabel.setAlignment(java.awt.Label.CENTER);
        headerLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        headerLabel.setText("Manage Customers");

        custIDLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        custIDLabel.setText("Customer ID");

        custIDTxt.setBackground(new java.awt.Color(102, 102, 102));
        custIDTxt.setForeground(new java.awt.Color(255, 255, 255));

        custTitleLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        custTitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        custTitleLabel.setText("Customer Title");

        descriptionTxt.setBackground(new java.awt.Color(102, 102, 102));
        descriptionTxt.setForeground(new java.awt.Color(255, 255, 255));

        customerNameLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        customerNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        customerNameLabel.setText("Customer Name");

        custNameTxt.setBackground(new java.awt.Color(102, 102, 102));
        custNameTxt.setForeground(new java.awt.Color(255, 255, 255));

        dobLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        dobLabel.setForeground(new java.awt.Color(0, 0, 0));
        dobLabel.setText("Date of Birth");

        salaryLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        salaryLabel.setForeground(new java.awt.Color(0, 0, 0));
        salaryLabel.setText("Salary");

        qohTxt.setBackground(new java.awt.Color(102, 102, 102));
        qohTxt.setForeground(new java.awt.Color(255, 255, 255));

        unitPriceTxt.setBackground(new java.awt.Color(102, 102, 102));
        unitPriceTxt.setForeground(new java.awt.Color(255, 255, 255));

        deleteCustBtn.setBackground(new java.awt.Color(51, 153, 255));
        deleteCustBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteCustBtn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        deleteCustBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteCustBtn.setLabel("Delete Customer");
        deleteCustBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCustBtnActionPerformed(evt);
            }
        });

        updateCustBtn.setBackground(new java.awt.Color(51, 153, 255));
        updateCustBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateCustBtn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        updateCustBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateCustBtn.setLabel("Update Customer");
        updateCustBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustBtnActionPerformed(evt);
            }
        });

        saveCustBtn.setBackground(new java.awt.Color(51, 153, 255));
        saveCustBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveCustBtn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        saveCustBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveCustBtn.setLabel("Save Customer");

        customerTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(customerTbl);

        custAddressLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        custAddressLabel.setText("Customer Address");

        custAddressTxt.setBackground(new java.awt.Color(102, 102, 102));
        custAddressTxt.setForeground(new java.awt.Color(255, 255, 255));

        cityLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cityLabel.setForeground(new java.awt.Color(0, 0, 0));
        cityLabel.setText("City");

        cityTxt.setBackground(new java.awt.Color(102, 102, 102));
        cityTxt.setForeground(new java.awt.Color(255, 255, 255));

        provinceLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        provinceLabel.setForeground(new java.awt.Color(0, 0, 0));
        provinceLabel.setText("Province");

        provinceTxt.setBackground(new java.awt.Color(102, 102, 102));
        provinceTxt.setForeground(new java.awt.Color(255, 255, 255));

        postalCodeTxt.setBackground(new java.awt.Color(102, 102, 102));
        postalCodeTxt.setForeground(new java.awt.Color(255, 255, 255));

        postalCodeLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        postalCodeLabel.setForeground(new java.awt.Color(0, 0, 0));
        postalCodeLabel.setText("Postal Code");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1231, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(269, 269, 269))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(custIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(custIDTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(custTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descriptionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(custNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dobLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(unitPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(salaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(qohTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deleteCustBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(updateCustBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(saveCustBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(148, 148, 148))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(custAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(custAddressTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(provinceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(provinceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(postalCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(postalCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addGap(253, 253, 253))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(custIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(custIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(custTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descriptionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(customerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(custNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dobLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(unitPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(salaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qohTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(custAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(custAddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(provinceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(provinceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(postalCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(postalCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveCustBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteCustBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateCustBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteCustBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCustBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteCustBtnActionPerformed

    private void updateCustBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateCustBtnActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label cityLabel;
    private java.awt.TextField cityTxt;
    private java.awt.Label custAddressLabel;
    private java.awt.TextField custAddressTxt;
    private java.awt.Label custIDLabel;
    private java.awt.TextField custIDTxt;
    private java.awt.TextField custNameTxt;
    private java.awt.Label custTitleLabel;
    private java.awt.Label customerNameLabel;
    private javax.swing.JTable customerTbl;
    private java.awt.Button deleteCustBtn;
    private java.awt.TextField descriptionTxt;
    private java.awt.Label dobLabel;
    private java.awt.Label headerLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label postalCodeLabel;
    private java.awt.TextField postalCodeTxt;
    private java.awt.Label provinceLabel;
    private java.awt.TextField provinceTxt;
    private java.awt.TextField qohTxt;
    private java.awt.Label salaryLabel;
    private java.awt.Button saveCustBtn;
    private java.awt.TextField unitPriceTxt;
    private java.awt.Button updateCustBtn;
    // End of variables declaration//GEN-END:variables
    public void loadTable(){
        String [] columns = {"Customer ID", "Customer Title", "Customer Name", "Date of Birth", "Salary", "Customer Address", "City", "Province", "Postal Code"};
        DefaultTableModel dtm = new DefaultTableModel(columns, 0){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        customerTbl.setModel(dtm);
        try {
            ArrayList<CustomerDto> customerDtos = custController.getAll();
            for(CustomerDto customerDto : customerDtos){
                Object [] rows = {customerDto.getCustID(), customerDto.getCustTitle(), customerDto.getCustName(), customerDto.getDob(), customerDto.getSalary(),
                                  customerDto.getCustAddress(), customerDto.getCity(), customerDto.getProvince(), customerDto.getPostalCode()};
                dtm.addRow(rows);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,  e.getMessage());
        }
    }
}
